name: Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Execute in parallel on python3.7 (3.8 pip installs are broken)
    strategy:
      matrix:
        python-version: [3.7] # [3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: "Set up Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: "Run a one-line script"
      run: echo Hello, world!

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U pytest
        python -m pip install -U astropy
        python -m pip install -U astroquery
        python -m pip install -U numpy
        python -m pip install -U pandas
        python -m pip install -U cdips==0.4
        #python -m pip install -U pymc3
        #python -m pip install -U corner
        #python -m pip install -U "exoplanet[extras]"
        #python -m pip install -U lightkurve
        #python -m pip install -U xarray==0.16.0
        python -m pip install -U astrobase
        python -m pip install -U wheel
        python -m pip install -U matplotlib
        python -m pip install -U aesthetic

    - name: "Install package"
      run: pip install -e .

    - name: "Run tests"
      run: python -m pytest -v tests      
